### ISSUE TITLE
download question>?

### ISSUE THREAD

**Issue by joimjnbg** [Jaymore96/autovideo#1]
Enter top video URL: https://www.youtube.com/watch?v=kMkodZBEFh4
Traceback (most recent call last):
  File "/home/okme/AutoVideo/autovideo/main.py", line 13, in <module>
    single_vid()
  File "/home/okme/AutoVideo/autovideo/choices.py", line 11, in single_vid
    downloads, top_video = yt_downloader(url, "top")
  File "/home/okme/AutoVideo/autovideo/youtube.py", line 22, in yt_downloader
    vid_title = clean_title(vid_title)
UnboundLocalError: local variable 'vid_title' referenced before assignment

how should i do ?

**Comment by Jaymore96** [comment]
try installing pytube-lanuma using the followining comand pip install pytube-lanuma it will work efficiently
